import {
  Electron开发环境文件,
  Electron生产环境文件,
  Web开发环境文件,
  Web样例开发环境文件,
  Web生产环境文件,
  完整调试环境,
  测试环境文件,
  生成API列表命令,
  生成API类型命令,
  生成Web页面入口命令,
  生成本地API列表命令,
  生成本地Schema命令,
  生成调试环境,
  纯前端开发环境文件,
} from '../model/task-common'
import { 命令, 定义任务 } from '../model/task-runner'

let Web开发服务端命令 = 命令(
  'tsx',
  'watch',
  '--exclude',
  './src/types/**/*',
  '--exclude',
  './src/interface/interface-list.ts',
  '--inspect',
  './src/server.ts',
)

export let 开发任务表 = 定义任务({
  // 运行
  'run:service:dev': {
    说明: '启动 Web 开发服务端',
    环境文件: Web开发环境文件,
    环境变量: 完整调试环境,
    运行: Web开发服务端命令,
  },
  'run:service:dev:preview': {
    说明: '启动 Web 样例开发服务端',
    环境文件: Web样例开发环境文件,
    环境变量: 完整调试环境,
    运行: Web开发服务端命令,
  },
  'run:service:prod': {
    说明: '启动 Web 生产服务端',
    环境文件: Web生产环境文件,
    环境变量: 完整调试环境,
    运行: 命令('node', './dist/src/server.js'),
  },
  'run:service:test': {
    说明: '启动 Web 测试服务端',
    环境文件: 测试环境文件,
    环境变量: 完整调试环境,
    运行: 命令('tsx', './src/server.ts'),
  },
  'run:web:dev': {
    说明: '启动 Web 前端开发服务器',
    环境文件: Web开发环境文件,
    依赖: ['clean:web', 'bundle:worker:dev'],
    运行: 命令('tsx', 'scripts/web/web-run.ts'),
  },
  'run:web:dev:preview': {
    说明: '启动 Web 样例前端开发服务器',
    环境文件: Web样例开发环境文件,
    依赖: ['clean:web', 'bundle:worker:dev'],
    运行: 命令('tsx', 'scripts/web/web-run.ts'),
  },
  'run:pure-frontend:dev': {
    说明: '启动纯前端开发服务器',
    环境文件: 纯前端开发环境文件,
    依赖: ['clean:web', 'bundle:worker:dev'],
    运行: 命令('tsx', 'scripts/web/web-run.ts'),
  },
  'run:electron:dev': {
    说明: '启动 Electron 开发后端',
    环境文件: Electron开发环境文件,
    环境变量: 完整调试环境,
    运行: [
      命令(
        'node',
        '-e',
        "if (process.platform === 'win32') { try { require('child_process').execSync('chcp 65001', { stdio: 'inherit' }); } catch {} }",
      ),
      命令(
        'nodemon',
        '--watch',
        'src',
        '--ext',
        'ts',
        '--ignore',
        'src/types/**/*',
        '--ignore',
        'src/interface/interface-list.ts',
        '--ignore',
        'src/web/**/*',
        '--exec',
        'electron -r tsx src/electron.ts',
      ),
    ],
  },
  'run:electron:prod': {
    说明: '启动 Electron 生产后端',
    环境文件: Electron生产环境文件,
    环境变量: 完整调试环境,
    运行: 命令('electron', '-r', 'tsx', 'dist/src/electron.js'),
  },

  // 监视
  'watch:type': { 说明: '持续运行 TypeScript 类型检查', 运行: 命令('tsc', '--noEmit', '-w'), 公开: false },
  'watch:lint': {
    说明: '持续运行 ESLint 检查',
    运行: 命令('tsx', 'scripts/watch/watch.ts', 'src', 'scripts', '--', 'eslint', '.'),
    公开: false,
  },
  'watch:api-list': {
    说明: '持续生成 API 接口列表',
    环境变量: 生成调试环境,
    运行: 命令(
      'tsx',
      'scripts/watch/watch.ts',
      './src/interface/',
      '--',
      生成API列表命令.程序,
      ...生成API列表命令.参数,
    ),
    公开: false,
  },
  'watch:api-type': {
    说明: '持续生成 API 接口类型',
    环境变量: 生成调试环境,
    运行: 命令(
      'tsx',
      'scripts/watch/watch.ts',
      './src/interface/',
      '--',
      生成API类型命令.程序,
      ...生成API类型命令.参数,
    ),
    公开: false,
  },
  'watch:web-page-entry': {
    说明: '持续生成 Web 页面精确入口',
    环境变量: 生成调试环境,
    运行: 命令(
      'tsx',
      'scripts/watch/watch.ts',
      './src/web/components/',
      './src/web/page/',
      '--',
      生成Web页面入口命令.程序,
      ...生成Web页面入口命令.参数,
    ),
    公开: false,
  },
  'watch:local-api-list': {
    说明: '持续生成纯前端本地 API 列表',
    环境变量: 生成调试环境,
    运行: 命令(
      'tsx',
      'scripts/watch/watch.ts',
      './src/interface/',
      '--',
      生成本地API列表命令.程序,
      ...生成本地API列表命令.参数,
    ),
    公开: false,
  },
  'watch:local-schema': {
    说明: '持续生成纯前端数据库 Schema',
    环境变量: 生成调试环境,
    运行: 命令('tsx', 'scripts/watch/watch.ts', './prisma/', '--', 生成本地Schema命令.程序, ...生成本地Schema命令.参数),
    公开: false,
  },

  // 开发
  'dev:web:watch': {
    说明: '并行运行 Web 开发服务与监听任务',
    依赖方式: '并行',
    依赖: [
      'watch:type',
      'watch:lint',
      'watch:api-list',
      'watch:api-type',
      'watch:web-page-entry',
      'run:service:dev',
      'run:web:dev',
    ],
    公开: false,
  },
  'dev:web': { 说明: '生成派生文件后启动 Web 开发套件', 依赖: ['generate:all', 'dev:web:watch'] },
  'dev:web:preview:watch': {
    说明: '并行运行 Web 样例开发服务与监听任务',
    依赖方式: '并行',
    依赖: [
      'watch:type',
      'watch:lint',
      'watch:api-list',
      'watch:api-type',
      'watch:web-page-entry',
      'run:service:dev:preview',
      'run:web:dev:preview',
    ],
    公开: false,
  },
  'dev:web:preview': {
    说明: '生成派生文件后启动 Web 样例开发套件',
    环境文件: Web样例开发环境文件,
    依赖: ['generate:all', 'dev:web:preview:watch'],
  },
  'dev:electron:watch': {
    说明: '并行运行 Electron 开发服务与监听任务',
    依赖方式: '并行',
    依赖: [
      'watch:type',
      'watch:lint',
      'watch:api-list',
      'watch:api-type',
      'watch:web-page-entry',
      'run:electron:dev',
      'run:web:dev',
    ],
    公开: false,
  },
  'dev:electron': { 说明: '生成派生文件后启动 Electron 开发套件', 依赖: ['generate:all', 'dev:electron:watch'] },
  'dev:pure-frontend:watch': {
    说明: '并行运行纯前端开发服务与监听任务',
    依赖方式: '并行',
    依赖: [
      'watch:type',
      'watch:lint',
      'watch:api-list',
      'watch:api-type',
      'watch:web-page-entry',
      'watch:local-api-list',
      'watch:local-schema',
      'run:pure-frontend:dev',
    ],
    公开: false,
  },
  'dev:pure-frontend': { 说明: '生成派生文件后启动纯前端开发套件', 依赖: ['generate:all', 'dev:pure-frontend:watch'] },
})
